export const initialMockCalls = [
  {
    id: 1,
    customer_name: "Acme Operations",
    phone_number: "+1 312 555 0101",
    call_date: "2026-04-20 09:15:00",
    duration_seconds: 482,
    sentiment: "Positive",
    status: "Reviewed",
    summary: "Customer asked about expanding seats for the support team.",
    next_step: "Send team pricing overview.",
  },
  {
    id: 2,
    customer_name: "BrightPath Dental",
    phone_number: "+1 415 555 0102",
    call_date: "2026-04-21 11:30:00",
    duration_seconds: 319,
    sentiment: "Neutral",
    status: "New",
    summary: "Customer needed clarification about monthly reporting exports.",
    next_step: "Share reporting documentation.",
  },
  {
    id: 3,
    customer_name: "Northstar Logistics",
    phone_number: "+1 206 555 0103",
    call_date: "2026-04-22 14:05:00",
    duration_seconds: 742,
    sentiment: "Negative",
    status: "Follow up",
    summary: "Customer reported delays getting onboarding questions answered.",
    next_step: "Schedule onboarding recovery call.",
  },
  {
    id: 4,
    customer_name: "Harbor Cafe Group",
    phone_number: "+1 617 555 0104",
    call_date: "2026-04-23 10:45:00",
    duration_seconds: 265,
    sentiment: "Positive",
    status: "Reviewed",
    summary: "Customer liked dashboard visibility and asked for manager access.",
    next_step: "Create manager invite.",
  },
  {
    id: 5,
    customer_name: "Summit Legal",
    phone_number: "+1 212 555 0105",
    call_date: "2026-04-24 16:20:00",
    duration_seconds: 531,
    sentiment: "Neutral",
    status: "New",
    summary: "Customer compared the product with an existing spreadsheet workflow.",
    next_step: "Send migration checklist.",
  },
  {
    id: 6,
    customer_name: "Cedar Health",
    phone_number: "+1 303 555 0106",
    call_date: "2026-04-25 13:10:00",
    duration_seconds: 408,
    sentiment: "Positive",
    status: "Reviewed",
    summary: "Customer confirmed the call review workflow fits their team process.",
    next_step: "Prepare trial closeout notes.",
  },
  {
    id: 7,
    customer_name: "Atlas Retail",
    phone_number: "+1 702 555 0107",
    call_date: "2026-04-26 15:55:00",
    duration_seconds: 615,
    sentiment: "Negative",
    status: "Follow up",
    summary: "Customer was confused about user roles and permissions.",
    next_step: "Walk through role setup.",
  },
  {
    id: 8,
    customer_name: "Greenline HVAC",
    phone_number: "+1 813 555 0108",
    call_date: "2026-04-27 08:40:00",
    duration_seconds: 352,
    sentiment: "Neutral",
    status: "New",
    summary: "Customer asked whether call summaries can be edited by supervisors.",
    next_step: "Explain review workflow.",
  },
  {
    id: 9,
    customer_name: "Pioneer Fitness",
    phone_number: "+1 512 555 0109",
    call_date: "2026-04-28 12:25:00",
    duration_seconds: 278,
    sentiment: "Positive",
    status: "Reviewed",
    summary: "Customer praised faster visibility into missed follow-ups.",
    next_step: "Ask for pilot feedback quote.",
  },
  {
    id: 10,
    customer_name: "Metro Property Care",
    phone_number: "+1 646 555 0110",
    call_date: "2026-04-29 17:35:00",
    duration_seconds: 689,
    sentiment: "Neutral",
    status: "Follow up",
    summary: "Customer wanted a clearer process for assigning next steps.",
    next_step: "Demo assignment workflow.",
  },
];
